<?php

namespace ContainerK49OuLp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_H_PakHGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.h.PakHG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.h.PakHG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'request' => ['privates', '.errored..service_locator.h.PakHG.Symfony\\component\\HttpFoundation\\Request', NULL, 'Cannot autowire service ".service_locator.h.PakHG": it references class "Symfony\\component\\HttpFoundation\\Request" but no such service exists.'],
        ], [
            'request' => 'Symfony\\component\\HttpFoundation\\Request',
        ]);
    }
}
