<?php

namespace ContainerK49OuLp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRequestService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.h.PakHG.Symfony\component\HttpFoundation\Request' shared service.
     *
     * @return \Symfony\component\HttpFoundation\Request
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.h.PakHG": it references class "Symfony\\component\\HttpFoundation\\Request" but no such service exists.');
    }
}
